name: ArtStanding
favicon: null
layout_spectrum: 0.62878
typography_spectrum: 0.58325
title: We Stand For Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151314'
    - '#ffffff'
    - '#50534c'
    - '#d5c8bf'
    - '#e64236'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
